name: Docker Build


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
   
defaults:
  run:
    shell: 'bash'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Enable experimental docker features
      run: |
        sudo rm -rf /etc/docker/daemon.json
        echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - name: Build and Publish
      env:
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        USERNAME: 'joeamedeo'
        IMAGE: 'ble-midi-drums'
        STAGE: 'builder'
      run: ./scripts/buildAndPublish.sh -u=${{ env.USERNAME }} -p=${{ env.PASSWORD }} -i=${{ env.IMAGE }} -v=${{ env.VERSION }} -t=${{ env.STAGE }}