name: Docker Build and Publish


on:
  release:
    types:
      - created
   
defaults:
  run:
    shell: 'bash'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log in to Docker
      env:
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        USERNAME: 'joeamedeo'
      run: docker login -u ${{ env.USERNAME }} -p ${{ env.PASSWORD }}
    
    - name: Build and Publish
      env:
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        USERNAME: 'joeamedeo'
        IMAGE: 'ble-midi-drums'
        GOOS: 'linux'
        CGO_ENABLED: 0
        GOARCHL: 'arm'
      run: docker buildx build --platform linux/arm -t ${{ env.USERNAME }}/${{ env.IMAGE }}:latest -t ${{ env.USERNAME }}/${{ env.IMAGE }}:${{ env.RELEASE_VERSION }} . --push