name: Docker Build


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
   
defaults:
  run:
    shell: 'bash'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish
      env:
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        USERNAME: 'joeamedeo'
        IMAGE: 'ble-midi-drums'
        VERSION: ${GITHUB_REF#refs/*/}
        STAGE: 'Builder'
      run: ./scripts/buildAndPublish.sh -u=${{ env.USERNAME }}, -p=${{ env.PASSWORD }} -i=${{ env.IMAGE }} -v=${{ env.VERSION }} -t=${{ env.STAGE }}